import Head from 'next/head'
import '../styles/globals.scss'


function MyApp({ Component, pageProps }) {

  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="/styles/globals.scss" />
    </Head>

    <Component {...pageProps} />
  </>
}

export default MyApp
